### ISSUE TITLE
Add GitHub Build action

### ISSUE THREAD

**Issue by matthew-n** [tcartwright/SqlServer.Rules#17]
We can ticket out the work. 

- [x] Convert projects to SDK style (This works for all except the DB project, unless we use [SDK Style SqlProj](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/170))
- [x] Add build pipeline
_Originally posted by @tcartwright in https://github.com/tcartwright/SqlServer.Rules/discussions/14#discussioncomment-1135885_

**Comment by tcartwright** [comment]
SDK style project conversion done.

**Comment by tcartwright** [comment]
Can we enforce c# xml comments match our needed format on build?

**Comment by tcartwright** [comment]
Build pipeline is mostly done. We are still working on the powershell that will create the markdown.
