### ISSUE TITLE
Add XML Docs to core clas files

### ISSUE THREAD

**Issue by matthew-n** [tcartwright/SqlServer.Rules#19]
Add docs to the following:

- [ ] SqlServer.Rules/SqlServerRule.cs
- [ ] SqlServer.Rules/ReferentialIntegrity/RIUtils.cs
- [ ] SqlServer.Rules/ReferentialIntegrity/JoinInfo.cs
- [ ] SqlServer.Rules/ReferentialIntegrity/ForeignKeyInfo.cs
- [ ] SqlServer.Rules/Globals/ModelInfo.cs
- [ ] SqlServer.Rules/Globals/Ignorables.cs
- [ ] SqlServer.Rules/Globals/Constants.cs
- [ ] SqlServer.Rules/BaseSqlCodeAnalysisRule.cs

**Comment by tcartwright** [comment]
I don't think we need to do these. We really only need to do the rules that have the rule attribute.
