### ISSUE TITLE
Refactor docs generator to find .dll from csproj file

### ISSUE THREAD

**Issue by delgertome** [tcartwright/SqlServer.Rules#41]
- [x] The documentation generator should not need the hardcoded path to the DLL file. The values are available from the csproj file.
- [ ] Extend logging
- [ ] Add table to Table of Contents: Friendly Name | Ignorable | Message
- [ ] Modify docs generator script to take in the new $GITHUB_BUILD_OUTPUT_DLL variable and remove all hard coded references to "SQLServer.Rules.dll" or "SQLServer.Rules". Infer all those values from the path passed in.

**Comment by tcartwright** [comment]
Also add more logging please. :)

**Comment by tcartwright** [comment]
Wrote a new ps to extract the info from the project file. I have a need for it as well to auto create a release if I can figure it out.
